name: angular_ui
version: 0.0.1
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
description: Angular-UI for Angular2.
homepage: http://akserg.github.io/angular.dart.ui
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  angular2: '>=2.0.0-alpha.6 <3.0.0'
  logging_handlers: '>=0.8.0 <0.9.0'
dev_dependencies:
  dartmocks: '>= 0.5.0'
  guinness: '>= 0.1.3'
transformers:
- $dart2js:
    commandLineOptions:
    - --enable-experimental-mirrors
